name: update-indexes

on: [push]

jobs:
  pages-directory-indexing:
    runs-on: ubuntu-latest
    name: Directory Index Updating
    steps:
      # Checkout repo
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Install python
      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10" # install the python version needed

      # We could install packages if needed.
      # - name: install python packages
      #   run: |
      #     python -m pip install --upgrade pip
      #     pip install -r requirements.txt

      # running the script
      - name: run python indexer
        run: python random_stuff/html_indexer.py

      # commiting changes (--allow-empty incase there is no changes)
      - name: commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git diff-index --quiet HEAD || (git commit -a -m "Chore: Updated index - Action" --allow-empty)

      # pushing - uses auto generated token.
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
