name: scripts-exec

on: [push]

jobs:
  python-scripts-execution:
    env:
      STEAM_ID: ${{ secrets.STEAM_ID }}
      STEAM_WEB_API_KEY: ${{ secrets.STEAM_WEB_API_KEY }}

    runs-on: ubuntu-latest
    name: Python Scripts Execution
    steps:
      # Checkout repo
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Install python
      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10" # install the python version needed

      # We could install packages if needed.
      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r random_stuff/requirements.txt

      # setup git
      - name: setup git
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

      # Update steam games
      - name: Steam Games Updating
        run: python random_stuff/steam_games.py

      # Update index
      - name: run python indexer
        run: python random_stuff/html_indexer.py

      # commiting changes (--allow-empty incase there is no changes)
      - name: commit changes
        run: |
          git add -A
          git diff-index --quiet HEAD || (git commit -a -m "Chore: Ran Scripts - Action" --allow-empty)

      # pushing - uses auto generated token.
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
